---
title: ES6 Promise总结并实现一个Promise
subtitle: 深入理解Promise
catalog: true
header-img: es6.jpg
date: 2019-12-17 17:37:33
tags:
- javascript
- 基础
- ES6
catagories:
- javascript
- 基础
- ES6
---

## ES6 Promise 总结并实现一个Promise

### Promise使用总结
####  Promise 的含义
Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。

#### Promise 就是一个状态机

三种状态
- pending（进行中）
- fulfilled（已成功）
- rejected（已失败）

状态转变
- 初始化处于 pending 状态
- 调用 resolve() 之后，pending -> fulfilled
- 调用 reject() 之后，pending -> rejected

Promise的特点：
- 对象的状态不受外界影响
- 一旦状态改变，就不会再变

#### 基本用法
Promise是一个构造函数，所以需要用new实例化返回一个promise的对象，可以直接在后面调用then，也可以在promise对象身上调用then。

Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。
```
const promise = new Promise((resolve, reject) => {
    //实例化的同时就已经触发执行了
    console.log(/*最早执行*/)
    //模拟异步操作
    setTimeout(() => {
        if (/*true*/) {
            resolve(/*给then回调传参*/)
        } else {
            reject(/*给catch回调传参*/)
        }
    }, 2000)
}).then((/*resolve给的参数*/) => {
    console.log(/*resolve给的参数*/)
}).catch((/*给catch回调传参*/) => {
    console.log(/*给catch回调传参*/)
})
```
Promise实例化接受的函数内部，是在实例化的同时就已经执行啦。

then方法第二个参数是可选的，是reject()执行后触发执行的回调函数，可以省略，直接用catch代替。

resolve函数接受的<font color=red>参数</font>是会传递给then方法里面的回调函数作为参数的。catch可以捕获链式调用前面的错误，也可以获取reject传的的参数。

#### Promise.prototype.then()
Promise 实例具有then方法，也就是说，then方法是定义在原型对象，then方法返回的是一个Promise的实例，不是原来的Promise实例，而是一个全新的实例。因此then方法后面还可以继续调用then方法。前一个then接收的回调函数return的返回值，直接传递到下一个then接收的回调函数作为参数。如果前一个回调中返回的是一个promise对象，那么后一个then需要等到返回的promise变化后才会执行。
```
new Promise((resolve, reject) => {
    setTimeout(() => {
        resove(1)
    },1000)
}).then((value) => {
    console.log(value) // 1
    return 2
}).then((value) => {
    console.log(value) // 2
})
```
#### Promise.all()
Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
```
const p = Promise.all([p1, p2, p3]).then((values)=>{
    console.log(values); //values是p1,p2,p3 resolve接受的参数的数组，如果某一个实例没有传参，则为数组对应的位置是undefind
}).catch((err)=>{
    console.log(err); // err是p1,p2,p3中第一个reject接受的参数，不是数组
})
```
接受一个数组为参数，数组中元素都是Promise的实例（如果不是，会调用Promise.resolve方法）。只有当所有Promise实例全部转变成 fulfilled 状态后，p才会变成fulfilled状态，只要有一个实例rejected，p的状态就变成rejected状态。

注意，如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
#### Promise.race()
Promise.race()方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
```
const p = Promise.race([p1, p2, p3]).then((value)=>{
    console.log(value); //value是p1,p2,p3中第一个resolve接受的参数，不是数组
}).catch((errs)=>{
    console.log(errs); // errs是p1,p2,p3 reject接受的参数的数组，如果某一个实例没有传参，则为数组对应的位置是undefind
})
```
接受一个数组为参数，数组中元素都是Promise的实例（如果不是，会调用Promise.resolve方法）。只要其中一个Promise实例转变成 fulfilled 状态，p 就会变成fulfilled状态，只有全部实例都rejected，p的状态才会变成rejected状态。

#### Promise.allSettled()
Promise.allSettled()方法接受一组 Promise 实例作为参数，包装成一个新的 Promise 实例。只有等到所有这些参数实例都返回结果，不管是fulfilled还是rejected，包装实例才会结束。该方法由 ES2020 引入。
```
const resolved = Promise.resolve(42);
const rejected = Promise.reject(-1);

const allSettledPromise = Promise.allSettled([resolved, rejected]);

allSettledPromise.then(function (results) {
  console.log(results);
});
// [
//    { status: 'fulfilled', value: 42 },
//    { status: 'rejected', reason: -1 }
// ]
```
有时候，我们不关心异步操作的结果，只关心这些操作有没有结束。这时，Promise.allSettled()方法就很有用。如果没有这个方法，想要确保所有操作都结束，就很麻烦。Promise.all()方法无法做到这一点。
#### Promise.resolve()
有时需要将现有对象转为 Promise 对象，Promise.resolve()方法就起到这个作用。
```
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```
参数
- 参数是 Promise 实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例。
- 参数是一个thenable对象，则将这个对象转为 Promise 对象，然后就立即执行thenable对象的then方法。
- 参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的 Promise 对象，状态为resolved。
- 调用时不带参数，直接返回一个resolved状态的 Promise 对象。

#### Promise.reject()
Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。
```
const p = Promise.reject('出错了');
// 等同于
const p = new Promise((resolve, reject) => reject('出错了'))

p.then(null, function (s) {
  console.log(s)
});
// 出错了
```

### 实现一个Promise
#### Promise的构造函数
1. 由于后面会多次涉及到this实例对象，为了避免混乱直接用self拿到this代表的实例对象。
2. 由于promise实例或涉及到3个状态，所以需要有一个status属性保存状态。
3. resolve/reject会接受参数并传递给then接受的回调函数中做参数，所以需要一个data属性存放这个值。
4. 当Promise实例状态转变之后，会执行then中的回调函数，所以需要两个保存回调的数组，至于为什么是数组，后面会举例说明。
5. 当Promise实例化之后，构造函数收到回调函数会立即执行，因此需要立即执行fn函数，由于可能会出现报错（throw Error）所以需要用到 try catch
6. 构造函数传入的回调函数在执行的时候需要 resolve 和 reject 两个函数作为参数，因此这两个函数也是在构造函数中定义的。

```
function PromiseX (fn) {

    // 避免后面this混乱
    const self = this;

    // 保存Promise实例状态
    self.status = 'pending';

    // 保存传递的参数数据
    self.data = '';

    // Promise resolve/reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    // 非链式调用会出现多个，具体后面举例
    self.onResolvedQueue = [];
    self.onRejectedQueue = [];

    // 实例化立即执行fn
    try{
        fn(resolve,reject)
    } catch (e) {
        reject(e)
    }

    function resolve () {
        ....
    }
    function reject () {
        ....
    }
}
```

#### resolve reject 函数实现
resolve和reject实际上是在 Promise 接收到 fn 回调函数中执行的。

一般情况下是 fn 中的异步操作结束返回结果后，成功了 resolve(value)，失败了 reject(reason)。
```
new Promise((resolve, reject) => {
    console.log(111)
    // 模拟异步操作
    setTimeout(() => {
        resolve(222)
    }, 2000)
}).then((value) => {
    console.log(value)
})
```

也有的情况不是异步操作，直接就调用了。

```
new Promise((resolve, reject) => {
    console.log(111)
    resolve(222)
}).then((value) => {
    console.log(value)
})
```
总之是Promise实例状态需要转变的时候就会调用他们了。
1. 当状态要变化的时候，实际还没有变化，所以状态应该还是 pending 状态
2. 将self.status转移到对应的状态。
3. 需要把接收到的参数给self.data存起来.
4. 状态转移完了，参数也保存完了，就需要执行then中的回调函数了

```
function PromiseX (fn) {
    //....

    function resolve (value) {
        if (selft.status === 'pending') {
            self.status = 'fulfilled';
            self.data = value;
            self.onResolvedQueue.forEach(resolved => resolved(value));
        }
    }
    function reject (reason) {
        if (selft.status === 'pending') {
            self.status = 'rejected';
            self.data = reason;
            self.onRejectedQueue.forEach(rejected => rejected(reason));
        }
    }
}
```

#### then 方法
Promise实例有一个then方法，是状态转变后的回调，很明显是应该写在原型上。具体使用上面有介绍。
1. then方法调用后，立即就会进入执行阶段。
2. then方法接受两个回调函数：一个是resolve后执行的，一个是reject后执行的，第二个可以省略。所以先判断两个是否是 function。
3. 如果构造函数实例化的时候接受的回调函数里面有异步操作的话，then执行是先于状态转变的，也就是 then 被调用的时候，Promise对象状态是 pending，大部分都是这种情况。这个时候就需要把then的回调推入Promise实例对象的执行队列中，等待状态转变后执行。
4. then方法返回的是一个新的 Promise 实例。当then的回调有return的时候，如果return的是Promise实例对象的话，那么then后跟的then（实际是then里的回调）就需要等待这个Promise实例对象状态转变后执行，如果return的是其他的话，其他会被Promise.resolve方法包裹，然后立即执行后面的then。 
5. 如果构造函数实例化的时候接受的回调函数里面<font color=red>没有</font>异步操作的话，直接调用了 resolve/reject，在Promise实例化的时候状态就已经转变了成 fulfilled/rejected 了，也就是说then 被调用的时候，状态已经不是 pending 了。

```
PromiesX.prototype.then = function (onResolve,onReject) {
    const self = this;
    onResolve = typeof onResolve === 'function' ? onResolve : function () {};
    onReject = typeof onReject === 'function' ? onReject : function () {};

    if(self.status === 'pending'){
        return new PromiseX ((resolve,reject) => {
            // 因为状态未转变，所以成功与失败的回调都需要推进队列
            self.onResolvedQueue.push(function(){
                try{
                    const x = onResolve(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            })
                
            self.onRejectedQueue.push(function(){
                try{
                    const x = reject(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            })
                
        })
    }

    if (self.status === 'fulfilled') {
        return new Promise((resolve,reject) => {
            try{
                const x = onResolve(self.data);
                if (x instanceof PromiseX) {
                    x.then(resovle, reject)
                } else {
                    resolve(x)
                }
            } catch (e) {
                reject(e)
            }
        })
    }

    if (self.status === 'fulfilled') {
        return new Promise((resolve,reject) => {
            try{
                const x = reject(self.data);
                if (x instanceof PromiseX) {
                    x.then(resovle, reject)
                } else {
                    resolve(x)
                }
            } catch (e) {
                reject(e)
            }
        })
    }
}

// catch实际上就是then方法第一个参数传null
Promise.prototype.catch = function (onRejected) {
    return this.then(null, onRejected)
}
```

#### 穿透
上面基本上就是一个基本能用的Promise实现了，看一下下面的代码,运行完成是可以alert 8的，也就是说8 穿透了多个 then 方法。但实际上，上面的代码是 undefined
```
new Promise(resolve=>resolve(8))
  .then()
  .then()
  .then(function foo(value) {
    alert(value)
  })
```
那么问题出在了哪里呢，实际上是中间的then方法没有接到参数,根据下面的代码，onResolve
和onReject没有传，所以赋值为空function啦，只要把参数向下传递就好了
```
onResolve = typeof onResolve === 'function' ? onResolve : function () {};
onReject = typeof onReject === 'function' ? onReject : function () {};
```
改成
```
onResolve = typeof onResolve === 'function' ? onResolve : value => value;
onReject = typeof onReject === 'function' ? onReject : reason => {throw reason};
```

#### 其他Promise方法

#### Promise.resolve
返回一个fulfilled状态的promise对象
```
Promise.resolve = function (reason) {
    return new Promise((resolve,reject) => {
        resolve(reason)
    })
}
```
#### Promise.rejected
返回一个rejected状态的promise对象
```
Promise.reject = function (reason) {
    return new Promise((resolve,reject) => {
        reject(reason)
    })
}
```

#### Promise.all
接收一个promise对象数组为参数 只有全部 promise 进入 fulfilled 状态才会继续后面的处理 通常会用来处理 多个并行异步操作
```
Promise.all = function ([p1,p2,p3]) {
  return new Promise((resolve, reject) => {
    let values = []
    let count = 0
    [p1,p2,p3].forEach((promise, index) => {
      promise.then(value => {
        console.log('value:', value, 'index:', index)
        values[index] = value
        count++
        if (count === [p1,p2,p3].length) {
          resolve(values)
        }
      }, reject)
    })
  })
}

```
#### Promise.race
接收一个promise对象数组为参数 Promise.race 只要有一个promise对象进入 fulfilled 或者 rejected 状态的话，就会继续进行后面的处理
```
Promise.race = function ([p1,p2,p3]) {
  return new Promise((resolve, reject) => {
      [p1,p2,p3].forEach((promise) => {
         promise.then(resolve, reject);
      });
  });
}
```
#### 最后完整的代码
原则上，promise.then(onResolved, onRejected)里的这两个函数需要异步调用，关于这一点，标准里也有说明：

>In practice, this requirement ensures that onFulfilled and onRejected execute asynchronously, after the event loop turn in which then is called, and with a fresh stack.

所以我们需要对我们的代码做一点变动，即在四个地方加上setTimeout(fn, 0)

Tip: 我们这里增加setTimeout，涉及到js执行栈以及js单线程和eventLoop相关的知识，各位对js的执行栈、js单线程、eventLoop不太了解的，可以谷歌查阅下相关资料，后边我有空也会写一篇js执行栈、js的单线程、eventloop的讲解文章。下面的代码中，我也会简单写一些加入setTimeout的原因分析。

```
function PromiseX (fn) {
    const self = this;
    self.status = 'pending';
    self.data = '';
    self.onResolvedQueue = [];
    self.onRejectedQueue = [];

    try{
        fn(resolve,reject)
    } catch (e) {
        reject(e)
    }

    function resolve (value) { //value成功态时接收的终值
        if (value instanceof PromiseX) {
            value.then(resolve, reject);
            return;
        }

        // 为什么resolve 加setTimeout? 见下文
        setTimeout(()=>{
            if (selft.status === 'pending') {
                self.status = 'fulfilled';
                self.data = value;
                self.onResolvedQueue.forEach(resolved => resolved(value));
            }
        }, 0)

    }
    function reject (reason) {
        setTimeout(() => {
            if (selft.status === 'pending') {
                self.status = 'rejected';
                self.data = reason;
                self.onRejectedQueue.forEach(rejected => rejected(reason));
            }
        }, 0);
    }
}

PromiesX.prototype.then = function (onResolve,onReject) {
    const self = this;
    onResolve = typeof onResolve === 'function' ? onResolve : value => value;
    onReject = typeof onReject === 'function' ? onReject : reason => {throw reason};

    if(self.status === 'pending'){
        return new PromiseX ((resolve,reject) => {
            // 因为状态未转变，所以成功与失败的回调都需要推进队列
            self.onResolvedQueue.push(function(){
                try{
                    const x = onResolve(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            })
                
            self.onRejectedQueue.push(function(){
                try{
                    const x = reject(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            })
                
        })
    }
    // then里面的fulfilled/rejected状态时 为什么要加setTimeout ?见下文
    if (self.status === 'fulfilled') {
        return new Promise((resolve,reject) => {
            setTimeout(() => {
                try{
                    const x = onResolve(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            }, 0);
        })
    }

    if (self.status === 'fulfilled') {
        return new Promise((resolve,reject) => {
            setTimeout(() => {
                try{
                    const x = reject(self.data);
                    if (x instanceof PromiseX) {
                        x.then(resovle, reject)
                    } else {
                        resolve(x)
                    }
                } catch (e) {
                    reject(e)
                }
            }, 0);

        })
    }
}

// catch实际上就是then方法第一个参数传null
Promise.prototype.catch = function (onRejected) {
    return this.then(null, onRejected)
}

Promise.resolve = function (reason) {
    return new Promise((resolve,reject) => {
        resolve(reason)
    })
}
Promise.reject = function (reason) {
    return new Promise((resolve,reject) => {
        reject(reason)
    })
}
Promise.all = function ([p1,p2,p3]) {
  return new Promise((resolve, reject) => {
    let values = []
    let count = 0
    [p1,p2,p3].forEach((promise, index) => {
      promise.then(value => {
        console.log('value:', value, 'index:', index)
        values[index] = value
        count++
        if (count === [p1,p2,p3].length) {
          resolve(values)
        }
      }, reject)
    })
  })
}
Promise.race = function ([p1,p2,p3]) {
  return new Promise((resolve, reject) => {
      [p1,p2,p3].forEach((promise) => {
         promise.then(resolve, reject);
      });
  });
}
```
#### 问题
- #### 为什么构造函数中 self.onResolvedQueue 和 self.onRejectedQueue 要用数组 ？

当下面这样非链式调用的时候会出现多个回调的情况
```
const promise1 = new Promise((resolve,reject) => {
    ...
});

promise1.then((value) => {
    console.log(value)
})

promise1.then((value) => {
    console.log(value)
})
```
- #### 为什么resolve 加setTimeout?

原因：

1. 2.2.4规范 onFulfilled 和 onRejected 只允许在 execution context 栈仅包含平台代码时运行.

2. 这里的平台代码指的是引擎、环境以及 promise 的实施代码。实践中要确保 onFulfilled 和 onRejected 方法异步执行，且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。

- #### then里面的FULFILLED/REJECTED状态时 为什么要加setTimeout ?

原因:

1. 其一 2.2.4规范 要确保 onFulfilled 和 onRejected 方法异步执行(且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行) 所以要在resolve里加上setTimeout

2. 其二 2.2.6规范 对于一个promise，它的then方法可以调用多次.（当在其他程序中多次调用同一个promise的then时 由于之前状态已经为fulfilled/rejected状态，则会走的下面逻辑),所以要确保为fulfilled/rejected状态后 也要异步执行onFulfilled/onRejected

3. 其三 2.2.6规范 也是resolve函数里加setTimeout的原因总之都是 让then方法异步执行 也就是确保onFulfilled/onRejected异步执行

### 参考
- [ECMAScript 6 入门](https://es6.ruanyifeng.com/#docs/promise)
- [Promise原理讲解 && 实现一个Promise对象 (遵循Promise/A+规范)](https://juejin.im/post/5aa7868b6fb9a028dd4de672)
- [从零一步一步实现一个完整版的Promise](https://juejin.im/post/5d59757f6fb9a06ae76405c6)